### ISSUE TITLE
能量机关滑动条调参，滑动条不断增加，直至内存溢出，程序终止

### ISSUE THREAD

**Issue by Que121** [wildwolf-team/WolfVision#82]
![image-20220718103951833](https://user-images.githubusercontent.com/97080652/179441867-25096cc5-8bc2-43f3-bc3f-2c34fd3710bd.png)
@roboxxltd

**Comment by Mrjiong-ff** [comment]
请问你的Opencv版本是什么

**Comment by Que121** [comment]
4.5.5

**Comment by Mrjiong-ff** [comment]
![2022-07-20 11-47-20 的屏幕截图](https://user-images.githubusercontent.com/56230028/179892500-09cf0b17-f8b8-472a-884d-6fb0c985e815.png)
尝试将代码改成上图中的写法，再检查问题是否解决。

**Comment by Que121** [comment]
收到了，谢谢！

**Comment by Que121** [comment]
已更改：
![2022-07-23_16-24_1](https://user-images.githubusercontent.com/97080652/180597163-780f4515-e76a-41fd-84f9-d0103a821a2a.png)

bug仍然存在，更改为以上写法后：
![2022-07-23_16-24](https://user-images.githubusercontent.com/97080652/180597133-411eae67-159d-4155-94c0-fc6a5fc4d9e7.png)

报错日志为：
![2022-07-23_16-24_2](https://user-images.githubusercontent.com/97080652/180597173-9c7af620-aa3e-437b-9b9d-260c2bbde036.png)

**Comment by Que121** [comment]
收到了，谢谢！
